# 1. Indexing

In [1]:
## https://www.youtube.com/watch?v=ZB7BZMhfPgk

"""
https://www.scipy2019.scipy.org/tutorial-participant-instructions
"""
    
import numpy as np

In [2]:
a = np.array([[0,1,2,3],[10,11,12,13]])

In [3]:
a.shape # (rows, columns)

(2, 4)

In [4]:
a.size # element count

8

In [5]:
a.ndim # (number of dimensions)
""" 
 ---------> dim 1
 |
 |
 |
 v dim 0
"""

' \n ---------> dim 1\n |\n |\n |\n v dim 0\n'

In [6]:
a[1,3]

13

In [7]:
a[1,3] = -1
a

array([[ 0,  1,  2,  3],
       [10, 11, 12, -1]])

In [8]:
a[1] # address second (oneth) row using single index

array([10, 11, 12, -1])

# 2. Slicing

In [9]:
"""
var[lower:upper:step]

#             -5 -4  -3  -2  -1
# indices:     0  1   2   3   4
a = np.array([10, 11, 12, 13, 14])
"""

'\nvar[lower:upper:step]\n\n#             -5 -4  -3  -2  -1\n# indices:     0  1   2   3   4\na = np.array([10, 11, 12, 13, 14])\n'

In [10]:
a = np.array([10,11,12,13,14])
a[1:3]

array([11, 12])

In [11]:
a[1:-2]

array([11, 12])

In [12]:
a[-4:3] # wtf

array([11, 12])

 Omitting indices
 
 omitted boundaries are assumed to be the beginning (or end) of the list

In [13]:
a[:3] # grab first three elements

array([10, 11, 12])

In [14]:
a[-2:] # grab last two elements

array([13, 14])

In [15]:
a[::2] # every other (oick every two) element

array([10, 12, 14])

In [16]:
b = [[i for i in range(6)] for i in range(6)]

In [17]:
ba = np.arange(25).reshape(5,5)
ba

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [18]:
ba[:,1::2]

array([[ 1,  3],
       [ 6,  8],
       [11, 13],
       [16, 18],
       [21, 23]])

In [19]:
ba[-1]

array([20, 21, 22, 23, 24])

In [20]:
ba[1::2, :3:2]

array([[ 5,  7],
       [15, 17]])

# 3. Array Broadcasting
arrays with smaller dimentsion are broadcasted to match the larger arrays, without copying data.

In [21]:
import numpy as np
a = np.ones((3, 5))
a

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [22]:
b = np.ones((5, ))
b

array([1., 1., 1., 1., 1.])

In [23]:
b.reshape(1,5)

array([[1., 1., 1., 1., 1.]])

In [24]:
b[np.newaxis, :]

array([[1., 1., 1., 1., 1.]])

 Dimensions of size 1 are repeated without copying

In [25]:
c = a + b
c

array([[2., 2., 2., 2., 2.],
       [2., 2., 2., 2., 2.],
       [2., 2., 2., 2., 2.]])

In [26]:
# is logically equivalent to ...

tmp_b = b.reshape(1,5)
tmp_b_repeat = tmp_b.repeat(3, axis = 0)
c = a + tmp_b_repeat
c

array([[2., 2., 2., 2., 2.],
       [2., 2., 2., 2., 2.],
       [2., 2., 2., 2., 2.]])

In [27]:
a_strech = np.ones((5,1)) + np.ones((3))
a_strech

array([[2., 2., 2.],
       [2., 2., 2.],
       [2., 2., 2.],
       [2., 2., 2.],
       [2., 2., 2.]])

# 4. Array Calculation Methods

Mathematical functions

- sum, prod
- min, max, argmin, argmax
- ptp (max - min)

statistics

- mean, std, var

Truth value testing

- any all

In [28]:
a = np.array([[1,2,3],[4,5,6]])
a.sum()

21

In [29]:
a.sum(axis = 0)

array([5, 7, 9])

In [30]:
a.sum(axis = -1)

array([ 6, 15])

In [31]:
a.prod(axis = -1)

array([  6, 120])

In [32]:
a.ptp(axis = -1) # production

array([2, 2])

min/max  argmin/max  unraveling

In [39]:
a_mm = np.array([[2,3],[0,1]])
np.min(a_mm)

0

In [40]:
a_mm.min()

0

In [41]:
a_mm.max(axis = 0)

array([2, 3])

In [42]:
np.max(a_mm, axis = 1)

array([3, 1])

In [43]:
# the location of a min/max
# arg methods return the location in 1D, on a raveled index of the 
# original array
a_mm.argmax()

1

In [44]:
np.argmin(a_mm)

2

In [45]:
# un-flatten 1D locations
np.unravel_index(a_mm.argmax(), a.shape)

(0, 1)

# 5. where function

provide coordinates from matrix

In [46]:
b_whe = np.array([-1, 2, 5, 5])
np.where(b_whe == b_whe.max())

(array([2, 3], dtype=int64),)

In [47]:
np.where(b_whe > 0)

(array([1, 2, 3], dtype=int64),)