In [1]:
"""
https://www.youtube.com/watch?v=ZB7BZMhfPgk
https://github.com/enthought/Numpy-Tutorial-SciPyConf-2019

Wind Statistics
----------------

Topics: Using array methods over different axes, fancy indexing.

1. The data in 'wind.data' has the following format::

        61  1  1 15.04 14.96 13.17  9.29 13.96  9.87 13.67 10.25 10.83 12.58 18.50 15.04
        61  1  2 14.71 16.88 10.83  6.50 12.62  7.67 11.50 10.04  9.79  9.67 17.54 13.83
        61  1  3 18.50 16.88 12.33 10.13 11.17  6.17 11.25  8.04  8.50  7.67 12.75 12.71

   The first three columns are year, month and day.  The
   remaining 12 columns are average windspeeds in knots at 12
   locations in Ireland on that day.

   Use the 'loadtxt' function from numpy to read the data into
   an array.

2. Calculate the min, max and mean windspeeds and standard deviation of the
   windspeeds over all the locations and all the times (a single set of numbers
   for the entire dataset).

3. Calculate the min, max and mean windspeeds and standard deviations of the
   windspeeds at each location over all the days (a different set of numbers
   for each location)

4. Calculate the min, max and mean windspeed and standard deviations of the
   windspeeds across all the locations at each day (a different set of numbers
   for each day)

5. Find the location which has the greatest windspeed on each day (an integer
   column number for each day).

6. Find the year, month and day on which the greatest windspeed was recorded.

7. Find the average windspeed in January for each location.

You should be able to perform all of these operations without using a for
loop or other looping construct.

Bonus
~~~~~

1. Calculate the mean windspeed for each month in the dataset.  Treat
   January 1961 and January 1962 as *different* months. (hint: first find a
   way to create an identifier unique for each month. The second step might
   require a for loop.)

2. Calculate the min, max and mean windspeeds and standard deviations of the
   windspeeds across all locations for each week (assume that the first week
   starts on January 1 1961) for the first 52 weeks. This can be done without
   any for loop.

Bonus Bonus
~~~~~~~~~~~

Calculate the mean windspeed for each month without using a for loop.
(Hint: look at `searchsorted` and `add.reduceat`.)

Notes
~~~~~

These data were analyzed in detail in the following article:

   Haslett, J. and Raftery, A. E. (1989). Space-time Modelling with
   Long-memory Dependence: Assessing Ireland's Wind Power Resource
   (with Discussion). Applied Statistics 38, 1-50.


See :ref:`wind-statistics-solution`.
"""

"\nhttps://www.youtube.com/watch?v=ZB7BZMhfPgk\nhttps://github.com/enthought/Numpy-Tutorial-SciPyConf-2019\n\nWind Statistics\n----------------\n\nTopics: Using array methods over different axes, fancy indexing.\n\n1. The data in 'wind.data' has the following format::\n\n        61  1  1 15.04 14.96 13.17  9.29 13.96  9.87 13.67 10.25 10.83 12.58 18.50 15.04\n        61  1  2 14.71 16.88 10.83  6.50 12.62  7.67 11.50 10.04  9.79  9.67 17.54 13.83\n        61  1  3 18.50 16.88 12.33 10.13 11.17  6.17 11.25  8.04  8.50  7.67 12.75 12.71\n\n   The first three columns are year, month and day.  The\n   remaining 12 columns are average windspeeds in knots at 12\n   locations in Ireland on that day.\n\n   Use the 'loadtxt' function from numpy to read the data into\n   an array.\n\n2. Calculate the min, max and mean windspeeds and standard deviation of the\n   windspeeds over all the locations and all the times (a single set of numbers\n   for the entire dataset).\n\n3. Calculate the min, max 

In [2]:
import numpy as np
from numpy import loadtxt

wind_data = loadtxt("wind.data")
wind_data

array([[61.  ,  1.  ,  1.  , ..., 12.58, 18.5 , 15.04],
       [61.  ,  1.  ,  2.  , ...,  9.67, 17.54, 13.83],
       [61.  ,  1.  ,  3.  , ...,  7.67, 12.75, 12.71],
       ...,
       [78.  , 12.  , 29.  , ..., 16.42, 18.88, 29.58],
       [78.  , 12.  , 30.  , ..., 12.12, 14.67, 28.79],
       [78.  , 12.  , 31.  , ..., 11.38, 12.08, 22.08]])

In [3]:
wind_data.shape

(6574, 15)

In [4]:
dates = wind_data[:, :3]
data = wind_data[:, 3:]

print('2. Statistics over all values')
print(' min:', data.min())
print(' max:', data.max())
print(' mean:', data.mean())
print(' standard deviation:', data.std())
print()

2. Statistics over all values
 min: 0.0
 max: 42.54
 mean: 10.22837377040868
 standard deviation: 5.603840181095793



In [5]:
print('3. Statistics over all days at each location')
print('  min:', data.min(axis=0))
print('  max:', data.max(axis=0))
print('  mean:', data.mean(axis=0))
print('  standard deviation:', data.std(axis=0))
print()

3. Statistics over all days at each location
  min: [0.67 0.21 1.5  0.   0.13 0.   0.   0.   0.   0.04 0.13 0.67]
  max: [35.8  33.37 33.84 28.46 37.54 26.16 30.37 31.08 25.88 28.21 42.38 42.54]
  mean: [12.36371463 10.64644813 11.66010344  6.30627472 10.45688013  7.09225434
  9.7968345   8.49442044  8.49581838  8.70726803 13.121007   15.59946152]
  standard deviation: [5.61918301 5.26820081 5.00738377 3.60513309 4.93536333 3.96838126
 4.97689374 4.49865783 4.16746101 4.50327222 5.83459319 6.69734719]



In [6]:
## Calculate the min, max and mean windspeed and standard deviations of the
##   windspeeds across all the locations at each day (a different set of numbers
##   for each day)
print('4. Statistics over all locations for each day')
print('  min:', data.min(axis=1))
print('  max:', data.max(axis=1))
print('  mean:', data.mean(axis=1))
print('  standard deviation:', data.std(axis=1))
print()

4. Statistics over all locations for each day
  min: [9.29 6.5  6.17 ... 8.71 9.13 9.59]
  max: [18.5  17.54 18.5  ... 29.58 28.79 27.29]
  mean: [13.09666667 11.79833333 11.34166667 ... 14.89       15.3675
 15.4025    ]
  standard deviation: [2.5773188  3.28972854 3.50543348 ... 5.51175108 5.30456427 5.45971172]



In [7]:
## Find the location which has the greatest windspeed on each day (an integer
##   column number for each day).
print('5. Location of daily maximum')
print('  daily max location:', data.argmax(axis=1))
print()

5. Location of daily maximum
  daily max location: [10 10  0 ... 11 11  2]



In [8]:
## 6. Find the year, month and day on which the greatest windspeed was recorded.
daily_max = data.max(axis=1)
max_row = daily_max.argmax()
# Note: Another way to do this would be to use the unravel_index function
# which takes a linear index and convert it to a location given the shape
# of the array:
max_row, max_col = np.unravel_index(data.argmax(), data.shape)
# Or you could use "where", which identifies *all* the places where the max
# occurs, rather than just the first. Note that "where" returns two arrays in
# this case, instead of two integers.
max_row, max_col = np.where(data == data.max())


print('6. Day of maximum reading')
print('  Year:', int(wind_data[max_row, 0]))
print('  Month:', int(wind_data[max_row, 1]))
print('  Day:', int(wind_data[max_row, 2]))
print()

6. Day of maximum reading
  Year: 66
  Month: 12
  Day: 2



In [9]:
## 7. Find the average windspeed in January for each location.

januaries = dates[:, 1] ==  1
januaries

array([ True,  True,  True, ..., False, False, False])

In [10]:
wind_data[januaries].mean(axis = 0)

array([69.5       ,  1.        , 16.        , 14.86955197, 12.92166667,
       13.29962366,  7.19949821, 11.67571685,  8.05483871, 11.81935484,
        9.5094086 ,  9.54320789, 10.05356631, 14.55051971, 18.02876344])

In [11]:
# Bonus

# compute the month number for each day in the dataset
months = (wind_data[:, 0] - 61) * 12 + wind_data[:, 1] - 1

# we're going to use the month values as indices, so we need
# them to be integers
months = months.astype(int)

# get set of unique months
month_values = set(months)

# initialize an array to hold the result
monthly_means = np.zeros(len(month_values))

for month in month_values:
    # find the rows that correspond to the current month
    day_indices = (months == month)

    # extract the data for the current month using fancy indexing
    month_data = data[day_indices]

    # find the mean
    monthly_means[month] = month_data.mean()

    # Note: experts might do this all-in one
    # monthly_means[month] = data[months==month].mean()

# In fact the whole for loop could reduce to the following one-liner
# monthly_means = array([data[months==month].mean() for month in month_values])


print("Bonus 1.")
print("  mean:", monthly_means)
print()

Bonus 1.
  mean: [11.38064516 13.49235119 11.07236559  8.41116667  8.97341398  9.69827778
  9.0191129  10.78744624  9.98913889 11.47658602  8.97275    10.83540323
 12.13212366 13.59598214  9.18459677 10.11858333 10.2380914  10.37711111
  8.55392473 10.16247312  9.03233333  8.77284946  8.69958333 13.50424731
 11.39830645 12.1975     12.22680108 11.66697222 11.92016129  9.58397222
  7.97793011 10.62623656  9.61469444 11.98873656 12.01725    11.70376344
 10.54655914 12.30577586 11.08018817 10.82422222 12.1602957  10.19705556
  9.77325269  8.7486828   9.92152778  9.42801075 10.83275    11.8411828
 13.20513441  7.79008929 11.99360215 11.74033333 10.02645161  9.59919444
  8.48080645 10.34521505  9.49627778  9.66018817 12.38769444 11.65768817
 12.23252688 14.23779762 12.11698925 13.87783333 10.78344086  8.566
  9.38806452  8.20416667  8.61044444  8.80290323 11.60736111 14.09346774
 10.5730914  13.11553571 14.86959677 11.01230556 10.91604839  8.20327778
  9.31594086  8.75123656 10.46183333 13.

In [12]:
months

array([  0,   0,   0, ..., 215, 215, 215])

In [13]:
# Bonus 2.
# Extract the data for the first 52 weeks. Then reshape the array to put
# on the same line 7 days worth of data for all locations. Let Numpy
# figure out the number of lines needed to do so
weekly_data = data[:52 * 7].reshape(-1,7*12)

print('Bonus 2. Weekly statistics over all locations')
print('  min:', weekly_data.min(axis=1))
print('  max:', weekly_data.max(axis=1))
print('  mean:', weekly_data.mean(axis=1))
print('  standard deviation:', weekly_data.std(axis=1))
print()

Bonus 2. Weekly statistics over all locations
  min: [1.79 0.5  1.04 2.17 3.63 8.08 3.42 2.21 5.66 1.71 2.75 2.58 1.46 3.21
 1.54 0.83 1.38 3.83 1.04 3.33 1.63 3.29 3.21 1.58 2.88 4.42 3.54 2.67
 1.46 2.17 2.25 2.5  6.83 3.96 1.13 1.25 4.17 1.46 3.21 1.04 2.96 3.75
 2.21 1.71 1.33 0.63 2.88 1.92 3.13 5.46 0.58 0.42]
  max: [18.5  20.71 20.79 27.63 27.71 26.38 28.62 29.63 25.8  22.71 22.95 21.54
 22.5  18.29 16.17 21.09 17.5  28.08 26.63 15.96 20.96 17.96 19.83 25.25
 24.71 21.87 21.29 22.5  21.42 25.37 20.25 14.58 24.3  22.29 24.71 20.25
 33.09 20.96 23.21 19.62 21.04 33.45 30.88 23.58 20.41 32.71 22.58 23.75
 29.33 25.62 24.41 29.33]
  mean: [10.30154762  8.895       9.29952381 14.92047619 12.7902381  16.03654762
 13.69488095 11.7597619  13.05642857 10.07535714 12.7502381   9.80142857
 11.27690476  8.75619048  7.65988095  9.45642857  7.72511905 11.66607143
  9.49797619  7.80666667  7.18857143  9.00452381  8.875       9.0952381
 10.33083333 10.00547619 10.6002381  11.00452381  6.498333

In [14]:
weekly_data.shape

(52, 84)

In [15]:
"""
Calculate the mean windspeed for each month without using a for loop.
(Hint: look at `searchsorted` and `add.reduceat`.)

"""

# compute the month number for each day in the dataset
months = (wind_data[:, 0] - 61) * 12 + wind_data[:, 1] - 1

# find the indices for the start of each month
# this is a useful trick - we use range from 0 to the
# number of months + 1 and searchsorted to find the insertion
# points for each.
month_indices = np.searchsorted(months, np.arange(months[-1] + 2))

# now use add.reduceat to get the sum at each location
monthly_loc_totals = np.add.reduceat(data, month_indices[:-1])

# now use add to find the sum across all locations for each month
monthly_totals = monthly_loc_totals.sum(axis=1)

# now find total number of measurements for each month
month_days = month_indices[1:] - month_indices[:-1]
measurement_count = month_days * 12

# compute the mean
monthly_means = monthly_totals / measurement_count

print("Bonus Bonus")
print("  mean:", monthly_means)

# Notes: this method relies on the fact that the months are contiguous in the
# data set - the method used in the bonus section works for non-contiguous
# days.

Bonus Bonus
  mean: [11.38064516 13.49235119 11.07236559  8.41116667  8.97341398  9.69827778
  9.0191129  10.78744624  9.98913889 11.47658602  8.97275    10.83540323
 12.13212366 13.59598214  9.18459677 10.11858333 10.2380914  10.37711111
  8.55392473 10.16247312  9.03233333  8.77284946  8.69958333 13.50424731
 11.39830645 12.1975     12.22680108 11.66697222 11.92016129  9.58397222
  7.97793011 10.62623656  9.61469444 11.98873656 12.01725    11.70376344
 10.54655914 12.30577586 11.08018817 10.82422222 12.1602957  10.19705556
  9.77325269  8.7486828   9.92152778  9.42801075 10.83275    11.8411828
 13.20513441  7.79008929 11.99360215 11.74033333 10.02645161  9.59919444
  8.48080645 10.34521505  9.49627778  9.66018817 12.38769444 11.65768817
 12.23252688 14.23779762 12.11698925 13.87783333 10.78344086  8.566
  9.38806452  8.20416667  8.61044444  8.80290323 11.60736111 14.09346774
 10.5730914  13.11553571 14.86959677 11.01230556 10.91604839  8.20327778
  9.31594086  8.75123656 10.46183333 

In [16]:
monthly_means.shape

(216,)

In [17]:
months

array([  0.,   0.,   0., ..., 215., 215., 215.])

In [18]:
months.shape

(6574,)

In [19]:
month_indices

array([   0,   31,   59,   90,  120,  151,  181,  212,  243,  273,  304,
        334,  365,  396,  424,  455,  485,  516,  546,  577,  608,  638,
        669,  699,  730,  761,  789,  820,  850,  881,  911,  942,  973,
       1003, 1034, 1064, 1095, 1126, 1155, 1186, 1216, 1247, 1277, 1308,
       1339, 1369, 1400, 1430, 1461, 1492, 1520, 1551, 1581, 1612, 1642,
       1673, 1704, 1734, 1765, 1795, 1826, 1857, 1885, 1916, 1946, 1977,
       2007, 2038, 2069, 2099, 2130, 2160, 2191, 2222, 2250, 2281, 2311,
       2342, 2372, 2403, 2434, 2464, 2495, 2525, 2556, 2587, 2616, 2647,
       2677, 2708, 2738, 2769, 2800, 2830, 2861, 2891, 2922, 2953, 2981,
       3012, 3042, 3073, 3103, 3134, 3165, 3195, 3226, 3256, 3287, 3318,
       3346, 3377, 3407, 3438, 3468, 3499, 3530, 3560, 3591, 3621, 3652,
       3683, 3711, 3742, 3772, 3803, 3833, 3864, 3895, 3925, 3956, 3986,
       4017, 4048, 4077, 4108, 4138, 4169, 4199, 4230, 4261, 4291, 4322,
       4352, 4383, 4414, 4442, 4473, 4503, 4534, 45

In [20]:
month_days

array([31, 28, 31, 30, 31, 30, 31, 31, 30, 31, 30, 31, 31, 28, 31, 30, 31,
       30, 31, 31, 30, 31, 30, 31, 31, 28, 31, 30, 31, 30, 31, 31, 30, 31,
       30, 31, 31, 29, 31, 30, 31, 30, 31, 31, 30, 31, 30, 31, 31, 28, 31,
       30, 31, 30, 31, 31, 30, 31, 30, 31, 31, 28, 31, 30, 31, 30, 31, 31,
       30, 31, 30, 31, 31, 28, 31, 30, 31, 30, 31, 31, 30, 31, 30, 31, 31,
       29, 31, 30, 31, 30, 31, 31, 30, 31, 30, 31, 31, 28, 31, 30, 31, 30,
       31, 31, 30, 31, 30, 31, 31, 28, 31, 30, 31, 30, 31, 31, 30, 31, 30,
       31, 31, 28, 31, 30, 31, 30, 31, 31, 30, 31, 30, 31, 31, 29, 31, 30,
       31, 30, 31, 31, 30, 31, 30, 31, 31, 28, 31, 30, 31, 30, 31, 31, 30,
       31, 30, 31, 31, 28, 31, 30, 31, 30, 31, 31, 30, 31, 30, 31, 31, 28,
       31, 30, 31, 30, 31, 31, 30, 31, 30, 31, 31, 29, 31, 30, 31, 30, 31,
       31, 30, 31, 30, 31, 31, 28, 31, 30, 31, 30, 31, 31, 30, 31, 30, 31,
       31, 28, 31, 30, 31, 30, 31, 31, 30, 31, 30, 31], dtype=int64)

In [21]:
month_indices.shape

(217,)

In [22]:
np.arange(months[-1]+2)

array([  0.,   1.,   2.,   3.,   4.,   5.,   6.,   7.,   8.,   9.,  10.,
        11.,  12.,  13.,  14.,  15.,  16.,  17.,  18.,  19.,  20.,  21.,
        22.,  23.,  24.,  25.,  26.,  27.,  28.,  29.,  30.,  31.,  32.,
        33.,  34.,  35.,  36.,  37.,  38.,  39.,  40.,  41.,  42.,  43.,
        44.,  45.,  46.,  47.,  48.,  49.,  50.,  51.,  52.,  53.,  54.,
        55.,  56.,  57.,  58.,  59.,  60.,  61.,  62.,  63.,  64.,  65.,
        66.,  67.,  68.,  69.,  70.,  71.,  72.,  73.,  74.,  75.,  76.,
        77.,  78.,  79.,  80.,  81.,  82.,  83.,  84.,  85.,  86.,  87.,
        88.,  89.,  90.,  91.,  92.,  93.,  94.,  95.,  96.,  97.,  98.,
        99., 100., 101., 102., 103., 104., 105., 106., 107., 108., 109.,
       110., 111., 112., 113., 114., 115., 116., 117., 118., 119., 120.,
       121., 122., 123., 124., 125., 126., 127., 128., 129., 130., 131.,
       132., 133., 134., 135., 136., 137., 138., 139., 140., 141., 142.,
       143., 144., 145., 146., 147., 148., 149., 15